"""change reason 'Approved' to 'approve'

Revision ID: 3c4be7a76606
Revises: 71f5dc8cf2ee
Create Date: 2026-08-13 18:08:10.364032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c4be7a76606'
down_revision: Union[str, Sequence[str], None] = '71f5dc8cf2ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
