"""feat: add 3CX call journaling and API key generation models and endpoints

Revision ID: 5127b53522c3
Revises: 6237b5a73eab
Create Date: 2026-08-19 07:01:25.882251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5127b53522c3'
down_revision: Union[str, Sequence[str], None] = '6237b5a73eab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
