"""feat: CRM  models and enpoints for 3CX integration

Revision ID: 6237b5a73eab
Revises: f2499a6fe586
Create Date: 2026-08-18 09:25:10.630902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6237b5a73eab'
down_revision: Union[str, Sequence[str], None] = 'f2499a6fe586'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
