"""add 'approved' to reason

Revision ID: 71f5dc8cf2ee
Revises: ed6ea1263b14
Create Date: 2026-08-13 18:06:42.525780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = '71f5dc8cf2ee'
down_revision: Union[str, Sequence[str], None] = 'ed6ea1263b14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='rejection_reason_enum',
        new_values=['APPROVED', 'INAPPROPRIATE_CONTENT', 'COPYRIGHT_VIOLATION', 'CRIMINAL_ACTIVITY'],
        affected_columns=[TableReference(table_schema='public', table_name='user_profiles', column_name='reason')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='rejection_reason_enum',
        new_values=['INAPPROPRIATE_CONTENT', 'COPYRIGHT_VIOLATION', 'CRIMINAL_ACTIVITY'],
        affected_columns=[TableReference(table_schema='public', table_name='user_profiles', column_name='reason')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
