"""initial model migration

Revision ID: b8efd17f244b
Revises: d9e569b248fd
Create Date: 2026-08-15 18:29:24.452914

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "b8efd17f244b"
down_revision: Union[str, Sequence[str], None] = "d9e569b248fd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tokens",
        sa.Column("refresh_token", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "user_agent", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True
        ),
        sa.Column(
            "client_ip", sqlmodel.sql.sqltypes.AutoString(length=45), nullable=True
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("is_revoked", sa.Boolean(), nullable=False),
        sa.Column("date_created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("date_modified", sa.DateTime(timezone=True), nullable=False),
        sa.Column("modified_by", sa.Integer(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["modified_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_tokens_expires_at"), "tokens", ["expires_at"], unique=False
    )
    op.create_index(
        op.f("ix_tokens_is_revoked"), "tokens", ["is_revoked"], unique=False
    )
    op.create_index(
        op.f("ix_tokens_refresh_token"), "tokens", ["refresh_token"], unique=True
    )
    op.create_index(op.f("ix_tokens_user_id"), "tokens", ["user_id"], unique=False)
    op.drop_index(op.f("ix_user_tokens_expires_at"), table_name="user_tokens")
    op.drop_index(op.f("ix_user_tokens_is_revoked"), table_name="user_tokens")
    op.drop_index(op.f("ix_user_tokens_refresh_token"), table_name="user_tokens")
    op.drop_index(op.f("ix_user_tokens_user_id"), table_name="user_tokens")
    op.drop_table("user_tokens")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_tokens",
        sa.Column("refresh_token", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "user_agent", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
        sa.Column(
            "client_ip", sa.VARCHAR(length=45), autoincrement=False, nullable=True
        ),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("is_revoked", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "date_created",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "date_modified",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("modified_by", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "expires_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["modified_by"], ["users.id"], name=op.f("user_tokens_modified_by_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("user_tokens_user_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("user_tokens_pkey")),
    )
    op.create_index(
        op.f("ix_user_tokens_user_id"), "user_tokens", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_user_tokens_refresh_token"),
        "user_tokens",
        ["refresh_token"],
        unique=True,
    )
    op.create_index(
        op.f("ix_user_tokens_is_revoked"), "user_tokens", ["is_revoked"], unique=False
    )
    op.create_index(
        op.f("ix_user_tokens_expires_at"), "user_tokens", ["expires_at"], unique=False
    )
    op.drop_index(op.f("ix_tokens_user_id"), table_name="tokens")
    op.drop_index(op.f("ix_tokens_refresh_token"), table_name="tokens")
    op.drop_index(op.f("ix_tokens_is_revoked"), table_name="tokens")
    op.drop_index(op.f("ix_tokens_expires_at"), table_name="tokens")
    op.drop_table("tokens")
    # ### end Alembic commands ###
