"""rename model 'user_profiles' to 'profiles''

Revision ID: ca3aad3ab787
Revises: 3c4be7a76606
Create Date: 2026-08-13 21:26:38.962844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'ca3aad3ab787'
down_revision: Union[str, Sequence[str], None] = '3c4be7a76606'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bio_recording_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('profile_picture_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('age_category', postgresql.ENUM('EMERGING_ADULT', 'EARLY_ADULT', 'PRIME_ADULT', 'MID_ADULT', 'MATURE_ADULT', 'SENIOR', name='age_category_enum', create_type=False), nullable=False),
    sa.Column('status', postgresql.ENUM('APPROVED', 'REJECTED', 'PENDING', 'ACTIVE', 'INACTIVE', 'SUSPENDED', name='profile_status_enum', create_type=False), nullable=False),
    sa.Column('reason', postgresql.ENUM('APPROVED', 'INAPPROPRIATE_CONTENT', 'COPYRIGHT_VIOLATION', 'CRIMINAL_ACTIVITY', name='rejection_reason_enum', create_type=False), nullable=True),
    sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('date_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date_modified', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['modified_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profiles_user_id'), 'profiles', ['user_id'], unique=True)
    op.drop_index(op.f('ix_user_profiles_user_id'), table_name='user_profiles')
    op.drop_table('user_profiles')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profiles',
    sa.Column('bio_recording_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('profile_picture_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('comment', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('age_category', postgresql.ENUM('EMERGING_ADULT', 'EARLY_ADULT', 'PRIME_ADULT', 'MID_ADULT', 'MATURE_ADULT', 'SENIOR', name='age_category_enum', create_type=False), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('APPROVED', 'REJECTED', 'PENDING', 'ACTIVE', 'INACTIVE', 'SUSPENDED', name='profile_status_enum', create_type=False), autoincrement=False, nullable=False),
    sa.Column('reason', postgresql.ENUM('APPROVED', 'INAPPROPRIATE_CONTENT', 'COPYRIGHT_VIOLATION', 'CRIMINAL_ACTIVITY', name='rejection_reason_enum', create_type=False), autoincrement=False, nullable=True),
    sa.Column('date_created', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('date_modified', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('modified_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['modified_by'], ['users.id'], name=op.f('user_profiles_modified_by_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_profiles_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_profiles_pkey'))
    )
    op.create_index(op.f('ix_user_profiles_user_id'), 'user_profiles', ['user_id'], unique=True)
    op.drop_index(op.f('ix_profiles_user_id'), table_name='profiles')
    op.drop_table('profiles')
    # ### end Alembic commands ###
