"""initial model migration

Revision ID: d9e569b248fd
Revises:
Create Date: 2026-08-15 18:28:08.353821

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "d9e569b248fd"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column(
            "username", sqlmodel.sql.sqltypes.AutoString(length=12), nullable=False
        ),
        sa.Column(
            "first_name", sqlmodel.sql.sqltypes.AutoString(length=12), nullable=False
        ),
        sa.Column(
            "last_name", sqlmodel.sql.sqltypes.AutoString(length=12), nullable=False
        ),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("phone_number", sa.String(length=32), nullable=False),
        sa.Column("birth_date", sa.Date(), nullable=False),
        sa.Column(
            "gender",
            postgresql.ENUM("MALE", "FEMALE", name="gender_enum", create_type=False),
            nullable=True,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "hashed_password", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "role",
            postgresql.ENUM(
                "ADMIN", "MODERATOR", "USER", name="user_role_enum", create_type=False
            ),
            nullable=True,
        ),
        sa.Column("date_joined", sa.DateTime(timezone=True), nullable=False),
        sa.Column("date_modified", sa.DateTime(timezone=True), nullable=False),
        sa.Column("modified_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["modified_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(
        op.f("ix_users_phone_number"), "users", ["phone_number"], unique=True
    )
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "profiles",
        sa.Column(
            "bio_recording_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column(
            "profile_picture_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "age_category",
            postgresql.ENUM(
                "EMERGING_ADULT",
                "EARLY_ADULT",
                "PRIME_ADULT",
                "MID_ADULT",
                "MATURE_ADULT",
                "SENIOR",
                name="age_category_enum",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            postgresql.ENUM(
                "APPROVED",
                "REJECTED",
                "PENDING",
                "INACTIVE",
                "SUSPENDED",
                name="profile_status_enum",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "reason",
            postgresql.ENUM(
                "INAPPROPRIATE_CONTENT",
                "COPYRIGHT_VIOLATION",
                "CRIMINAL_ACTIVITY",
                name="rejection_reason_enum",
                create_type=False,
            ),
            nullable=True,
        ),
        sa.Column("comment", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("date_created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("date_modified", sa.DateTime(timezone=True), nullable=False),
        sa.Column("modified_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["modified_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_profiles_user_id"), "profiles", ["user_id"], unique=True)
    op.create_table(
        "user_tokens",
        sa.Column("refresh_token", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "user_agent", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True
        ),
        sa.Column(
            "client_ip", sqlmodel.sql.sqltypes.AutoString(length=45), nullable=True
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("is_revoked", sa.Boolean(), nullable=False),
        sa.Column("date_created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("date_modified", sa.DateTime(timezone=True), nullable=False),
        sa.Column("modified_by", sa.Integer(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["modified_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_tokens_expires_at"), "user_tokens", ["expires_at"], unique=False
    )
    op.create_index(
        op.f("ix_user_tokens_is_revoked"), "user_tokens", ["is_revoked"], unique=False
    )
    op.create_index(
        op.f("ix_user_tokens_refresh_token"),
        "user_tokens",
        ["refresh_token"],
        unique=True,
    )
    op.create_index(
        op.f("ix_user_tokens_user_id"), "user_tokens", ["user_id"], unique=False
    )
    op.sync_enum_values(
        enum_schema="public",
        enum_name="profile_status_enum",
        new_values=["APPROVED", "REJECTED", "PENDING", "INACTIVE", "SUSPENDED"],
        affected_columns=[
            TableReference(
                table_schema="public", table_name="profiles", column_name="status"
            )
        ],
        enum_values_to_rename=[],
    )
    op.sync_enum_values(
        enum_schema="public",
        enum_name="rejection_reason_enum",
        new_values=[
            "INAPPROPRIATE_CONTENT",
            "COPYRIGHT_VIOLATION",
            "CRIMINAL_ACTIVITY",
        ],
        affected_columns=[
            TableReference(
                table_schema="public", table_name="profiles", column_name="reason"
            )
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="public",
        enum_name="rejection_reason_enum",
        new_values=[
            "APPROVED",
            "INAPPROPRIATE_CONTENT",
            "COPYRIGHT_VIOLATION",
            "CRIMINAL_ACTIVITY",
        ],
        affected_columns=[
            TableReference(
                table_schema="public", table_name="profiles", column_name="reason"
            )
        ],
        enum_values_to_rename=[],
    )
    op.sync_enum_values(
        enum_schema="public",
        enum_name="profile_status_enum",
        new_values=[
            "APPROVED",
            "REJECTED",
            "PENDING",
            "ACTIVE",
            "INACTIVE",
            "SUSPENDED",
        ],
        affected_columns=[
            TableReference(
                table_schema="public", table_name="profiles", column_name="status"
            )
        ],
        enum_values_to_rename=[],
    )
    op.drop_index(op.f("ix_user_tokens_user_id"), table_name="user_tokens")
    op.drop_index(op.f("ix_user_tokens_refresh_token"), table_name="user_tokens")
    op.drop_index(op.f("ix_user_tokens_is_revoked"), table_name="user_tokens")
    op.drop_index(op.f("ix_user_tokens_expires_at"), table_name="user_tokens")
    op.drop_table("user_tokens")
    op.drop_index(op.f("ix_profiles_user_id"), table_name="profiles")
    op.drop_table("profiles")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_phone_number"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
