"""feat: add more models and enpoints

Revision ID: f2499a6fe586
Revises: cd6a2c32d361
Create Date: 2026-08-17 17:33:57.659415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'f2499a6fe586'
down_revision: Union[str, Sequence[str], None] = 'cd6a2c32d361'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('PUBLISHED', 'DRAFT', 'ARCHIVED', 'DELETED', 'SUSPENDED', name='post_status_enum').create(op.get_bind())
    sa.Enum('DOCUMENT', 'PHOTO', 'AUDIO', 'VIDEO', name='media_type_enum').create(op.get_bind())
    op.create_table('posts',
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('parent_post_id', sa.Integer(), nullable=True),
    sa.Column('status', postgresql.ENUM('PUBLISHED', 'DRAFT', 'ARCHIVED', 'DELETED', 'SUSPENDED', name='post_status_enum', create_type=False), nullable=False),
    sa.Column('date_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date_modified', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['modified_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_posts_author_id'), 'posts', ['author_id'], unique=False)
    op.create_index(op.f('ix_posts_parent_post_id'), 'posts', ['parent_post_id'], unique=False)
    op.create_table('post_media',
    sa.Column('media_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('media_type', postgresql.ENUM('DOCUMENT', 'PHOTO', 'AUDIO', 'VIDEO', name='media_type_enum', create_type=False), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_media_post_id'), 'post_media', ['post_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_media_post_id'), table_name='post_media')
    op.drop_table('post_media')
    op.drop_index(op.f('ix_posts_parent_post_id'), table_name='posts')
    op.drop_index(op.f('ix_posts_author_id'), table_name='posts')
    op.drop_table('posts')
    sa.Enum('DOCUMENT', 'PHOTO', 'AUDIO', 'VIDEO', name='media_type_enum').drop(op.get_bind())
    sa.Enum('PUBLISHED', 'DRAFT', 'ARCHIVED', 'DELETED', 'SUSPENDED', name='post_status_enum').drop(op.get_bind())
    # ### end Alembic commands ###
